spring.application.name=concessionaria

server.port=8081
#banco
spring.datasource.url=sua_url_conexao
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha

#realiza alterações no banco de dados
spring.jpa.hibernate.ddl-auto=create
#mostrar as consultas sql que estão sendo executadas no banco de dados
spring.jpa.show-sql=true
#formatar as consultas sql que estão sendo executadas no banco de dados
spring.jpa.properties.hibernate.format_sql=true

#intervalo de tempo para verificar se houve alterações no código
spring.devtools.restart.poll-intervall=2s
spring.devtools.restart.quiet-period=2s
